# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.5
_src_path: gh:algorandfoundation/algokit-python-template
author_email: j.lewis@digitaldimension.com.mx
author_name: Jason Wade Lewis
contract_name: digital_marketplace
deployment_language: python
preset_name: production
project_name: digital_marketplace

